// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrW9nEIKhFcDbBDgDHltJcqVfgDmBzgc',
    appId: '1:417535061762:web:6b7ef8bb40b726488e5c1b',
    messagingSenderId: '417535061762',
    projectId: 'char-app-2887a',
    authDomain: 'char-app-2887a.firebaseapp.com',
    storageBucket: 'char-app-2887a.appspot.com',
    measurementId: 'G-DLNQ6S8F7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwooQyWz-Y947pzuTHaJgFxW49uC1rXQ',
    appId: '1:417535061762:android:8b1c9125b1aee3038e5c1b',
    messagingSenderId: '417535061762',
    projectId: 'char-app-2887a',
    storageBucket: 'char-app-2887a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5mhMMB3MBczCUNgt840f760jDa8rxceU',
    appId: '1:417535061762:ios:3a07699d8771ac798e5c1b',
    messagingSenderId: '417535061762',
    projectId: 'char-app-2887a',
    storageBucket: 'char-app-2887a.appspot.com',
    iosClientId: '417535061762-au5iu4q23qujn9l6osiq2cqr43m1vlr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
